# Generated by Django 4.2.2 on 2023-08-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_client.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('act_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=50)),
                ('act_price', models.IntegerField()),
                ('act_time', models.CharField(max_length=50)),
                ('act_des', models.CharField(max_length=200, null=True)),
                ('act_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('drinl_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=50)),
                ('drink_price', models.IntegerField()),
                ('drink_type', models.CharField(max_length=50)),
                ('drink_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hygien',
            fields=[
                ('hyg_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hyg_name', models.CharField(max_length=50)),
                ('hyg_price', models.IntegerField()),
                ('hyg_time', models.CharField(max_length=50)),
                ('hyg_des', models.CharField(max_length=200, null=True)),
                ('hyg_imge', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('meal_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=50)),
                ('meal_price', models.IntegerField()),
                ('meal_type', models.CharField(max_length=50)),
                ('meal_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('meal_des', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mouscronLocation',
            fields=[
                ('room_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
                ('room_picture1', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_picture2', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_picture3', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_time', models.CharField(default=user_client.models.default_mouscron)),
            ],
        ),
        migrations.CreateModel(
            name='tournaiLocation',
            fields=[
                ('room_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
                ('room_picture1', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_picture2', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_picture3', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('room_time', models.CharField(default=user_client.models.default_tournai)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_number', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('user_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='other', max_length=20, null=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_activation', models.BooleanField(blank=True, default=False, null=True)),
                ('user_DOB', models.DateField(blank=True, default=None, null=True)),
                ('user_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('res_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('res_details', models.CharField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, default='null', null=True)),
                ('payment_amount', models.IntegerField(default=0)),
                ('client_reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(default='dionslilospa@gmail.com', max_length=50)),
                ('emp_password', models.CharField(max_length=50)),
                ('user_employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_client.employee')),
            ],
        ),
    ]
