# Generated by Django 4.2.2 on 2023-08-30 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('formula_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula_name', models.CharField(max_length=50)),
                ('formula_price', models.IntegerField()),
            ],
        ),
    ]
