# Generated by Django 4.2.2 on 2023-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0003_alter_activities_act_time_alter_hygien_hyg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
