# Generated by Django 4.2.2 on 2023-09-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0004_formula_formula_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='res_details',
            field=models.JSONField(),
        ),
    ]
