# Generated by Django 4.2.2 on 2023-09-04 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0005_alter_reservations_res_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
