# Generated by Django 4.2.2 on 2023-09-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0006_reservations_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='check_people',
            field=models.CharField(default='half paid'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
